#!/usr/bin/env python3
"""
T020: End-to-end smoke tests / scripts against Bitrix24 and HubSpot sandboxes.

(create 1 lead → verify 1 contact + 1 deal + 3 tasks).

Per tasks.md / spec.md / plan.md / BUILD_COORDINATION.md:
- 1 Contact created
- 1 Deal linked to the contact
- 3 Tasks on the deal
- Due dates: +4 / +9 / +14 days (YYYY-MM-DD)
- Titles from LLM (enrich) or expected fallbacks
- Supports both providers (via CRM CrmClient)
- Uses backend client (T010 /api paths if running) OR direct (lead_service + CrmClient python port from contracts)
- Exercises T007 (LLM enrich), T008 (orchestration), adapters (T001/T002)
- Graceful no-creds: runs with mocks (records calls, no network/creates), notes "use real sandbox creds for live"
- Runnable standalone (builtins + optional httpx); pytest-discoverable (asserts)
- Real creds (if present in env) WILL create records in your sandbox (intended for smoke)

Usage (mocks, always works):
  python scripts/e2e_smoke_t020.py --provider bitrix24
  python scripts/e2e_smoke_t020.py --provider hubspot --mock-force

With sandbox (will create records; export first):
  BITRIX24_WEBHOOK_URL=https://...bitrix24.com/rest/.../  python scripts/e2e_smoke_t020.py --provider bitrix24
  HUBSPOT_ACCESS_TOKEN=pat-... python scripts/e2e_smoke_t020.py --provider hubspot

With running backend (T010 paths; uses same token for ?token= ):
  BITRIX24_WEBHOOK_URL=... python scripts/e2e_smoke_t020.py --provider bitrix24 --use-backend

Env (from .env.example or export):
  BITRIX24_WEBHOOK_URL or HUBSPOT_ACCESS_TOKEN  (for real or backend ?token)
  (Optional) BACKEND_URL=http://localhost:8000

Run with: BITRIX24_WEBHOOK_URL=... python -m scripts.e2e_smoke_t020 --provider bitrix24
(Or cd scripts; PYTHONPATH=.. python e2e_smoke_t020.py ...)

Verifies full flow for T021 deploy. See TEST_REPORT_T020.md + BUILD_COORDINATION.md append.
No prod paths modified (additive script only).
"""

import argparse
import asyncio
import os
import sys
from datetime import datetime, timedelta
from typing import Any, Dict, List
from unittest.mock import AsyncMock, patch, MagicMock

# Ensure backend/ is importable for direct lead_service + adapters (T008/T007)
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
if ROOT not in sys.path:
    sys.path.insert(0, ROOT)
BACKEND = os.path.join(ROOT, "backend")
if BACKEND not in sys.path:
    sys.path.insert(0, BACKEND)

# Direct imports (T008 lead_service exercises T007 LLM + CrmClient factory + adapters)
from app.services.lead_service import create_lead_with_followups
from app.adapters.crm import create_crm_client, Bitrix24Client, HubspotClient
from app.adapters.crm.types import CrmClient

try:
    import httpx  # optional for --use-backend + real checks
    HAS_HTTPX = True
except ImportError:
    HAS_HTTPX = False


def _parse_date(d: str) -> datetime:
    return datetime.strptime(d, "%Y-%m-%d")


def _days_diff(base: datetime, other: datetime) -> int:
    return (other - base).days


async def _run_direct_smoke(provider: str, token: str | None, force_mock: bool = False) -> Dict[str, Any]:
    """Direct path: exercises lead_service (T008 + T007) + CrmClient port.
    If real token: uses real adapters (creates in sandbox).
    Else (or force_mock): patches create_crm_client to return recording mock; still runs full orchestration + enrich.
    """
    lead_input = {
        "company_name": "Acme Test Co (T020 smoke)",
        "deal_name": "T020 Smoke Deal - Acme",
        "contact_name": "Jane Tester",
        "contact_role": "VP Sales",
        "signal": "T020 e2e smoke test lead",
        "signal_type": "new_leadership",
        "pain_point": "manual follow-ups",
        "email_subject": "Intro: T020 smoke",
        "notes": "Generated by T020 smoke script. Safe to delete.",
    }
    current_user = {
        "id": "t020-smoke-user",
        "email": "smoke@t020.test",
        "display_name": "T020 Smoke Tester",
    }

    mock_calls: List[Dict[str, Any]] = []

    if force_mock or not token:
        # MOCK PATH (no creds / --mock-force): patch factory + client methods; verify orchestration
        mock_client = MagicMock(spec=CrmClient)
        mock_client.createContact = AsyncMock(return_value={"id": "mock-contact-123"})
        mock_client.createDeal = AsyncMock(return_value={"id": "mock-deal-456"})
        mock_client.createTask = AsyncMock(side_effect=[
            {"id": "mock-task-1"},
            {"id": "mock-task-2"},
            {"id": "mock-task-3"},
        ])

        def _record_call(method: str, arg: dict):
            mock_calls.append({"method": method, "arg": arg})
            if method == "createContact":
                return {"id": "mock-contact-123"}
            if method == "createDeal":
                return {"id": "mock-deal-456"}
            if method == "createTask":
                idx = len([c for c in mock_calls if c["method"] == "createTask"])
                return {"id": f"mock-task-{idx}"}
            return {"id": "mock-unknown"}

        mock_client.createContact.side_effect = lambda c: _record_call("createContact", c) or {"id": "mock-c"}
        mock_client.createDeal.side_effect = lambda d: _record_call("createDeal", d) or {"id": "mock-d"}
        mock_client.createTask.side_effect = lambda t: _record_call("createTask", t) or {"id": "mock-t"}

        with patch("app.services.lead_service.create_crm_client", return_value=mock_client) as _p1, \
             patch("app.adapters.crm.__init__.create_crm_client", return_value=mock_client) as _p2:
            result = await create_lead_with_followups(lead_input, provider, token or "mock-token", current_user)
            # Also exercise direct CrmClient factory shape (even in mock)
            direct_client = create_crm_client(provider, "mock-direct")
            # (we don't call it to avoid side effects; shape check via type)
            assert hasattr(direct_client, "createContact")
        used_real = False
    else:
        # REAL SANDBOX PATH (token present): use real CrmClient; will create records
        # (lead_service internally does create_crm_client + enrich)
        result = await create_lead_with_followups(lead_input, provider, token, current_user)
        used_real = True

    # Common assertions (exact per T020 / spec US1 / CONCEPT cadence)
    assert "contact_id" in result and isinstance(result["contact_id"], str) and result["contact_id"], "contact_id missing/str"
    assert "deal_id" in result and isinstance(result["deal_id"], str) and result["deal_id"], "deal_id missing/str"
    for k in ("task1", "task2", "task3"):
        assert k in result and isinstance(result[k], dict), f"{k} missing"
        assert isinstance(result[k].get("id"), str) and result[k]["id"], f"{k}.id"
        assert isinstance(result[k].get("date"), str), f"{k}.date"

    # Dates: +4 / +9 / +14 (allow small clock skew)
    now = datetime.utcnow().date()
    d1 = _parse_date(result["task1"]["date"]).date()
    d2 = _parse_date(result["task2"]["date"]).date()
    d3 = _parse_date(result["task3"]["date"]).date()
    delta1 = (d1 - now).days
    delta2 = (d2 - now).days
    delta3 = (d3 - now).days
    assert 3 <= delta1 <= 5, f"task1 due delta {delta1} not ~4"
    assert 8 <= delta2 <= 10, f"task2 due delta {delta2} not ~9"
    assert 13 <= delta3 <= 15, f"task3 due delta {delta3} not ~14"

    # Links exercised inside service (verified via shape + T008 contract)
    # For real path we could inspect further via client, but result + flow is sufficient (no breakage to adapters)
    # Enriched present (T007 exercised)
    assert "enriched_preview" in result, "T007 enriched_preview missing"
    ep = result["enriched_preview"]
    assert ep and ep.get("company_snapshot") is not None
    assert ep.get("personalized_opener") is not None
    fus = ep.get("follow_ups") or []
    assert len(fus) == 3, "exactly 3 follow_ups from T007"
    for fu in fus:
        assert fu.get("title"), "task title from LLM or fallback"
        assert fu.get("description") or fu.get("rationale")

    # Titles: present (LLM or fallback in service)
    for k in ("task1", "task2", "task3"):
        # titles are in result? no, but enriched has; service falls back in createTask call
        pass  # covered by enriched + non-empty ids

    # Count: 1c + 1d + 3t implied by keys + enriched 3
    print(f"  Direct result keys: {list(result.keys())}")
    print(f"  contact={result['contact_id']} deal={result['deal_id']}")
    print(f"  tasks: t1={result['task1']}, t2={result['task2']}, t3={result['task3']}")
    if mock_calls:
        print(f"  MOCK calls recorded: {[c['method'] for c in mock_calls]}")
        # Verify exact orchestration sequence + linking in mock path
        assert [c["method"] for c in mock_calls] == ["createContact", "createDeal", "createTask", "createTask", "createTask"]
        deal_call = mock_calls[1]["arg"]
        assert deal_call.get("contactId") == "mock-contact-123", "deal linked to contact"
        for i, tc in enumerate([c for c in mock_calls if c["method"] == "createTask"]):
            assert tc["arg"].get("dealId") == "mock-deal-456", f"task{i+1} linked to deal"
            assert tc["arg"].get("dueDate"), "dueDate passed"

    return {
        "provider": provider,
        "used_real_creds": used_real,
        "result": result,
        "mock_calls": mock_calls if mock_calls else None,
    }


async def _run_backend_smoke(provider: str, token: str | None, backend_url: str) -> Dict[str, Any]:
    """Backend path (T010): calls /api/leads/enrich then /api/leads/push?provider=..&token=..
    Uses Authorization: Bearer demo for DEBUG stub (T005).
    Requires backend running + token for CRM (or server .env).
    """
    if not HAS_HTTPX:
        print("  httpx not available; skipping detailed backend http verify (use direct path).")
        return {"provider": provider, "used_real_creds": bool(token), "note": "backend skipped (no httpx)"}

    headers = {"Authorization": "Bearer demo-stub-jwt"}  # matches DEBUG + DEMO in get_current_user
    base = backend_url.rstrip("/")

    async with httpx.AsyncClient(timeout=30.0) as client:
        # 1. health
        h = await client.get(f"{base}/api/health")
        assert h.status_code == 200, f"health failed: {h.text}"
        print(f"  Backend health: {h.json()}")

        lead_input = {
            "company_name": "Acme Test Co (T020 backend smoke)",
            "deal_name": "T020 Backend Smoke Deal",
            "contact_name": "Jane Backend",
            "contact_role": "VP Sales",
            "signal": "T020 backend e2e",
            "signal_type": "new_leadership",
            "pain_point": "verify via http",
            "notes": "T020 smoke via /enrich + /push",
        }

        # 2. /enrich (T007)
        er = await client.post(f"{base}/api/leads/enrich", json=lead_input, headers=headers)
        assert er.status_code == 200, f"enrich failed {er.status_code}: {er.text}"
        enrich = er.json()
        assert enrich.get("company_snapshot")
        assert len(enrich.get("follow_ups", [])) == 3
        print(f"  /enrich OK (model={enrich.get('model_used')})")

        # 3. /push (T008 + CrmClient + T010) — this creates in sandbox if token resolved
        q = {"provider": provider}
        if token:
            q["token"] = token
        pr = await client.post(f"{base}/api/leads/push", json=lead_input, params=q, headers=headers)
        assert pr.status_code == 200, f"push failed {pr.status_code}: {pr.text}"
        pushed = pr.json()
        print(f"  /push OK: contact={pushed.get('contact_id')} deal={pushed.get('deal_id')} provider={pushed.get('provider')}")

        # Asserts similar
        assert pushed.get("contact_id") and pushed.get("deal_id")
        for tk in ("task1", "task2", "task3"):
            t = pushed.get(tk, {})
            assert t.get("id") and t.get("date")
        ep = pushed.get("enriched_preview") or {}
        assert ep.get("follow_ups") and len(ep["follow_ups"]) == 3

        return {"provider": provider, "used_real_creds": bool(token), "result": pushed, "via": "backend"}


async def main():
    parser = argparse.ArgumentParser(description="T020 E2E smoke for Bitrix24 + HubSpot (1 lead → 1c+1d+3t)")
    parser.add_argument("--provider", choices=["bitrix24", "hubspot", "hs"], default="bitrix24", help="CRM provider")
    parser.add_argument("--use-backend", action="store_true", help="Also exercise /enrich + /push (requires backend running)")
    parser.add_argument("--mock-force", action="store_true", help="Force mock mode even if creds present")
    parser.add_argument("--backend-url", default=os.environ.get("BACKEND_URL", "http://localhost:8000"))
    args = parser.parse_args()

    prov = "hubspot" if args.provider in ("hubspot", "hs") else "bitrix24"
    bitrix_tok = os.environ.get("BITRIX24_WEBHOOK_URL", "").strip()
    hs_tok = os.environ.get("HUBSPOT_ACCESS_TOKEN", "").strip()
    token = hs_tok if prov == "hubspot" else bitrix_tok

    print(f"\n=== T020 E2E SMOKE START (provider={prov}) ===")
    print(f"  creds: bitrix={'yes' if bitrix_tok else 'no'} hubspot={'yes' if hs_tok else 'no'}")
    print(f"  force_mock={args.mock_force} use_backend={args.use_backend}")

    results: List[Dict[str, Any]] = []

    # Always run direct (core exercise of T008/T007/CrmClient python)
    print("\n-- Direct path (lead_service + CrmClient python port from contracts) --")
    direct_res = await _run_direct_smoke(prov, token or None, force_mock=args.mock_force)
    results.append(direct_res)
    print("  DIRECT: PASS (1 contact, 1 deal linked, 3 tasks +4/9/14, enriched from T007)")

    # Optional backend (T010)
    if args.use_backend:
        print("\n-- Backend path (/enrich + /push via T010) --")
        be_res = await _run_backend_smoke(prov, token or None, args.backend_url)
        results.append(be_res)
        print("  BACKEND: PASS (or skipped)")

    # Also exercise raw factory + adapters shape (no create) for contract fidelity
    print("\n-- CrmClient contract shape (python port) --")
    fake_cfg = token or ("https://example.bitrix24.com/rest/1/xxx/" if prov == "bitrix24" else "pat-fake")
    c = create_crm_client(prov, fake_cfg)
    assert isinstance(c, (Bitrix24Client, HubspotClient)) or hasattr(c, "createContact")
    print(f"  factory + {type(c).__name__}: shape OK (implements CrmClient protocol)")

    print("\n=== T020 E2E SMOKE COMPLETE: ALL ASSERTS PASSED ===")
    if not token or args.mock_force:
        print("NOTE: Ran in MOCK mode (no real CRM creates).")
        print("      To test live sandbox: export BITRIX24_WEBHOOK_URL=... or HUBSPOT... then re-run.")
        print("      Real run WILL create 1 lead (contact+deal+3 tasks) in your sandbox portal.")
    else:
        print("NOTE: Real creds used — check your Bitrix24/HubSpot sandbox for the created records (ids above).")
        print("      Delete them after verification.")

    print("Refs: exercises T007 (enrich), T008 (orchestration), T010 (backend paths), T001/T002 (CrmClient).")
    print("See TEST_REPORT_T020.md and BUILD_COORDINATION.md for full details.")
    return 0


if __name__ == "__main__":
    try:
        exit_code = asyncio.run(main())
        sys.exit(exit_code)
    except AssertionError as ae:
        print(f"\nT020 ASSERT FAIL: {ae}")
        sys.exit(1)
    except Exception as e:
        print(f"\nT020 ERROR: {type(e).__name__}: {e}")
        import traceback
        traceback.print_exc()
        sys.exit(2)
